### PR TITLE
Add sanity check for output decomp

### PR DESCRIPTION
**Pull request by nopara73**
Explanation: https://github.com/zkSNACKs/WalletWasabi/issues/10759#issuecomment-1569910313

Draft, because Part 2 isn't yet implemented (that must be implemented to WalletWasabi not here)

### CODE REVIEW

**Comment by onvej-sl** [comment]
I think [this](https://github.com/nopara73/Sake/blob/625ed2d17d400ed96477b6162ca2db798454dec6/Sake/Mixer.cs#L421) is the best place to fix the bug. It's the only place where you call `Output.FromAmount` without checking whether the amount is at least `MinAllowedOutputAmount + ChangeFee`.

**Comment by onvej-sl** [comment]
The condition `denoms.Min(x => x.EffectiveCost) > myInputSum` may be too strict. An alternative is `MinAllowedOutputAmount + ChangeFee > myInputSum`.

**Comment by nopara73** [comment]
> denoms.Min(x => x.EffectiveCost) > myInputSum

Is it though? If the input sum is smaller than the cost of creating a single output of the smallest denomination, then the user gains no privacy, so makes no sense to participate at all?

> I think [this](https://github.com/nopara73/Sake/blob/625ed2d17d400ed96477b6162ca2db798454dec6/Sake/Mixer.cs#L421) is the best place to fix the bug.

- [x] I was actually considering removing that entire thing. It smells like a hack and if we ensure input sum adds up, then it's unnecessary.
 
 I bring https://github.com/zkSNACKs/WalletWasabi/issues/10759#issuecomment-1570124592 discussion here to create a ToDo:
 
- [x] The coin selection algorithm.

> This should prevent the situation when the algorithm selects coins whose effective value is less than MinAllowedOutputAmount + ChangeFee.
 
If we estimate the smallest possible denom, then we can have an even stricter condition. I know this won't prevent failure.

- [x] The amount decomposition algorithm.
> return [], sign the coinjoin transaction and sacrifice the input or
> throw an exception, refuse to sign the coinjoin transaction and disrupt the round.

I think both are correct. DoS vs user participating to sacrifice an input. Maybe sacrificing the input sounds slightly worse. Anyhow, this shouldn't really happen if the input side fix is done.

- [x] The algorithm that registers inputs.

> This should prevent the situation when the wallet fails to register some coins due to tor latency and the effective value of the remaining coins is less than MinAllowedOutputAmount + ChangeFee.

I hope this'll not be too difficult change to make.

**Comment by onvej-sl** [comment]
> Anyhow, this shouldn't really happen if the input side fix is done.

We can never prevent it, but I hope it will happen very rarely.

**Comment by nopara73** [comment]
https://github.com/nopara73/Sake/pull/38

**Pull request closed without merging**
