### PR TITLE
Use allowedOutputTypes instead of isTaprootAllowed

### PR DESCRIPTION
**Pull request by turbolay**
Mirror changes in https://github.com/zkSNACKs/WalletWasabi/pull/10842

### CODE REVIEW

**Comment by turbolay** [comment]
Do I need to implement `CalculateSmallestReasonableEffectiveDenomination`, and make sure that the sum of the inputs is higher than that? Maybe with some recursive loop or something like that.

**Comment by nopara73** [comment]
Yes, I think we should, otherwise testing higher feerates will give us exceptions. FTR I think you already added some kind of min input check into `Program.cs` before, since you're here, you may want to revisit that as well if it's correct.

**Comment by turbolay** [comment]
Yes I added the check of individual input, effective value > 0. I will add the check for sum of inputs as it's implemented in Wasabi's PR

**Comment by nopara73** [comment]
> Yes I added the check of individual input, effective value > 0

Ok, good, I didn't get it at the time when I reviewed, just went with the flow, but if you put it this way, it makes perfect sense.

**Comment by nopara73** [comment]
FTR you can test if you did it well if you set the fee rate at the `Program.cs` to 1000000m and then see if this exception comes: https://github.com/nopara73/Sake/pull/38/files#diff-572a300905f509dc0f52a04ecce34373059055360975ba901b7332a25723bf04R104

**Comment by nopara73** [comment]
Please do it in the next PR.

**Comment by turbolay** [comment]
I almost finished implementation of the subsequent PR today but it's time consuming and not perfect as we have to create groups of coins that respects a predicate.

The `remixRate` is fixed,but we can't know how many groups we will be able to create in the 2nd mix, as we are using outputs from the first round. Also we still have to form them randomly which means all big denominations will be slowly extracted and last groups will be harder and harder to form.

There is a decision to make between 3 solutions:

**First:**
Try to form inputs groups randomly with a max retry parameter. Whenever we retry too much (it's to difficult to create new groups) we just take existing groups to complete the selection and still respect remix rate. This solution uses some outputs several times.

**Second:**
Simply get random elements from the preMix output instead of forming groups. This solution also reuses outputs.

**Third:**
Consider this bug like a feature and display the remix rate evolving as a new metric to see if clients are able to remix properly.

**Comment by nopara73** [comment]
@turbolay for me, to fully understand your comment and the ramifications of the options you provide would likely take longer than fixing the bug itself. So, I am happy to leave this decision to you.

> Enlightenment is man's emergence from his self-imposed immaturity. Immaturity is the inability to use one's understanding without guidance from another.

**Pull request merged**
